### ISSUE TITLE
Proposal: Vehicle detection integration

### ISSUE THREAD

**Issue by jeffehobbs** [robmarkcole/HASS-Sighthound#13]
I have one of my cameras pointed at my driveway. Adding in an additional event for "vehicle detected" -- ideally passing the additional metadata representing the vehicle and license plate -- would allow me to know who is coming and going. We could even trigger automations based on specific license plates (!)

https://www.sighthound.com/docs/cloud/recognition/#vehicle-recognition

**Comment by clsferguson** [comment]
I second this. I just got my nvr system to process pictures through home-assistants internal sighthound component. So i did a google search to see if anyone added vehicles. Then i found this component. 

my coding skills are weak, lol. But before i try adding the vehicle stuff myself, can you add it?

**Comment by clsferguson** [comment]
As a suggestion;

it seems like for each type of image scan. it needs to use another api call. It would be good if the integration had two places to specify camera entities. One for people, one vehicles. then the ability to add a camera in both spots. that way if the camera can only people or only vehicles it can save api calls.

**Comment by robmarkcole** [comment]
As you mention this requires calling a different API endpoint, and would require a resonable amount of work. I think it would be better to have a seperate integration, rather than making one complex integration to handle vehicles and people. Ideally the vehicle integration would detect the vehicle and identify its number plate. [Note that number plate reading is already supported by HA](https://rc.home-assistant.io/integrations/openalpr_cloud/)

**Comment by robmarkcole** [comment]
Implement this, see https://github.com/home-assistant/core/blob/dev/homeassistant/components/openalpr_local/image_processing.py

**Comment by robmarkcole** [comment]
Done in https://github.com/robmarkcole/HASS-Sighthound/pull/18
